
#
# Build Config
#
build:
    environment:
        php: '5.4.28'
    cache:
        directories:
            - '~/.composer/'
    dependencies:
            before:
              - composer global require "fxp/composer-asset-plugin:~1.0"
    project_setup:
        before:
            - mysql -e "CREATE DATABASE scheduler_test;"
            - php tests/_app/yii migrate/up --interactive=0 --migrationPath=src/migrations/
    tests:
        before:
            - vendor/bin/codecept build
            - vendor/bin/codecept run || true # this is a dirty hack :(
        override:
           -
                command: 'vendor/bin/codecept run --coverage --coverage-xml --coverage-html'
                coverage:
                    file: 'tests/_output/coverage.xml'
                    format: 'php-clover'
#
# Analysis Config
##
filter:
    excluded_paths: [tests/*, src/models/base/*]
tools:
    php_analyzer: true
    php_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
