
#
# Build Config
#
build:
    environment:
        php: '5.4.28'
    cache:
        directories:
            - '~/.composer/'
    dependencies:
            before:
              - composer global require "fxp/composer-asset-plugin:~1.0"
    project_setup:
        before:
            - mysql -e "CREATE DATABASE scheduler_test;"
            - php tests/_app/yii migrate/up --interactive=0 --migrationPath=src/migrations/
    tests:
        before:
            - vendor/bin/codecept build
            - vendor/bin/codecept run --report --coverage-xml
#        override:
#            -
#                command:
#                coverage:
#                    file: 'codception/_output/coverage.xml'
#                    format: 'php-clover'
##
# Analysis Config
##
filter:
    excluded_paths: [tests/*, src/models/base/*]
tools:
  external_code_coverage: true
  php_analyzer: true
  php_mess_detector: true
  php_sim: true
  sensiolabs_security_checker: true
  php_changetracking: true
  php_cs_fixer:
      config: { level: psr2 }
checks:
  php:
    code_rating: true