filter:
    excluded_paths: [tests/*, src/models/base/*]

build:
    environment:
        php: '5.4.28'
    cache:
        directories:
            - '~/.composer/'
    dependencies:
            before:
              - composer global require "codeception/codeception:~2.0"
              - composer global require "fxp/composer-asset-plugin:~1.0"
    project_setup:
        before:
            - mysql -e "CREATE DATABASE scheduler_test;"
            - php tests/codeception/_app/yii migrate/up --interactive=0
    tests:
        before:
            - cd tests
            - ~/.composer/vendor/bin/codecept build
        override:
            - ~/.composer/vendor/bin/codecept run -v

